create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  stock integer not null default 0,
  category text not null check (category in ('air minum', 'gas', 'lainnya')),
  created_at timestamp with time zone default now()
);

create table if not exists customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  address text
);

create table if not exists drivers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  customer_id bigint references customers(id),
  order_type text not null check (order_type in ('store', 'delivery')),
  payment_method text not null check (payment_method in ('cash', 'transfer', 'qris')),
  transfer_proof_url text,
  total_price numeric not null,
  order_status text not null default 'pending' check (order_status in ('pending', 'diproses', 'dikirim', 'selesai')),
  driver_id bigint references drivers(id),
  created_at timestamp with time zone default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade,
  product_id bigint references products(id),
  quantity integer not null,
  price numeric not null
);
